"""versioned education plans

Revision ID: 7d1f0a6b3c29
Revises: 2b6d8f3a91c4
Create Date: 2026-07-29 12:59:47.508501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1f0a6b3c29'
down_revision = '2b6d8f3a91c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), server_default='OPEN', nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED','ARCHIVED')", name='ck_tariff_cycle_status'),
    sa.CheckConstraint('closed_at IS NULL OR opened_at IS NULL OR closed_at >= opened_at', name='ck_tariff_cycle_period'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariff_cycle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_cycle_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_cycle_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_tariff_cycle_scope_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_cycle_status'), ['status'], unique=False)
        batch_op.create_index('uq_tariff_cycle_global_year', ['academic_year_id'], unique=True, postgresql_where=sa.text('organization_id IS NULL'), sqlite_where=sa.text('organization_id IS NULL'))
        batch_op.create_index('uq_tariff_cycle_local_year', ['organization_id', 'academic_year_id'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'), sqlite_where=sa.text('organization_id IS NOT NULL'))

    op.create_table('tariff_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_cycle_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.String(length=40), server_default='BASE', nullable=False),
    sa.Column('status', sa.String(length=40), server_default='DRAFT', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('origin_version_id', sa.Integer(), nullable=True),
    sa.Column('reason_text', sa.String(length=500), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('effective_at', sa.DateTime(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','VALIDATION','APPROVAL','APPROVED','EFFECTIVE','SUPERSEDED','ARCHIVED')", name='ck_tariff_version_status'),
    sa.CheckConstraint("version_type IN ('BASE','CORRECTION','EMERGENCY')", name='ck_tariff_version_type'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name='ck_tariff_version_effective_period'),
    sa.CheckConstraint('revision > 0', name='ck_tariff_version_revision'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['origin_version_id'], ['tariff_version.id'], ),
    sa.ForeignKeyConstraint(['tariff_cycle_id'], ['tariff_cycle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_cycle_id', 'version_no', name='uq_tariff_version_cycle_number')
    )
    with op.batch_alter_table('tariff_version', schema=None) as batch_op:
        batch_op.create_index('ix_tariff_version_cycle_status', ['tariff_cycle_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_version_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_version_tariff_cycle_id'), ['tariff_cycle_id'], unique=False)

    op.create_table('education_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('plan_kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('education_level', sa.String(length=20), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('scope_code', sa.String(length=80), server_default='ALL', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("plan_kind IN ('CURRICULUM','EXTRACURRICULAR','ADDITIONAL_EDUCATION')", name='ck_education_plan_kind'),
    sa.CheckConstraint("status IN ('DRAFT','READY','LOCKED')", name='ck_education_plan_status'),
    sa.CheckConstraint('revision > 0', name='ck_education_plan_revision'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'plan_kind', 'scope_code', 'name', name='uq_education_plan_version_scope_name')
    )
    with op.batch_alter_table('education_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_plan_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_education_level'), ['education_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_plan_kind'), ['plan_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index('ix_education_plan_version_kind', ['tariff_version_id', 'plan_kind'], unique=False)

    op.create_table('tariff_version_status_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('DRAFT','VALIDATION','APPROVAL','APPROVED','EFFECTIVE','SUPERSEDED','ARCHIVED')", name='ck_tariff_version_history_from_status'),
    sa.CheckConstraint("to_status IN ('DRAFT','VALIDATION','APPROVAL','APPROVED','EFFECTIVE','SUPERSEDED','ARCHIVED')", name='ck_tariff_version_history_to_status'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariff_version_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_tariff_version_history_changed', ['tariff_version_id', 'changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_version_status_history_tariff_version_id'), ['tariff_version_id'], unique=False)

    op.create_table('education_plan_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_plan_id', sa.Integer(), nullable=False),
    sa.Column('education_activity_id', sa.Integer(), nullable=False),
    sa.Column('component_kind', sa.String(length=40), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('annual_hours', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('requires_division', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('profile_code', sa.String(length=80), nullable=True),
    sa.Column('source_line_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("component_kind IN ('MANDATORY','PARTICIPANT_FORMED','ELECTIVE','EXTRACURRICULAR','ADDITIONAL','OTHER')", name='ck_education_plan_line_component'),
    sa.CheckConstraint('(weekly_hours IS NOT NULL OR annual_hours IS NOT NULL) AND (weekly_hours IS NULL OR weekly_hours >= 0) AND (annual_hours IS NULL OR annual_hours >= 0)', name='ck_education_plan_line_hours'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['education_activity_id'], ['education_activity.id'], ),
    sa.ForeignKeyConstraint(['education_plan_id'], ['education_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_line_id'], ['education_plan_line.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('education_plan_line', schema=None) as batch_op:
        batch_op.create_index('ix_education_plan_line_activity_component', ['education_activity_id', 'component_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_line_component_kind'), ['component_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_line_education_activity_id'), ['education_activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_line_education_plan_id'), ['education_plan_id'], unique=False)

    op.create_table('education_plan_line_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_plan_line_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('weeks_count', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('weekly_hours', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('annual_hours', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.CheckConstraint('(weeks_count IS NULL OR weeks_count >= 0) AND (weekly_hours IS NULL OR weekly_hours >= 0) AND (annual_hours IS NULL OR annual_hours >= 0)', name='ck_education_plan_line_period_hours'),
    sa.CheckConstraint('date_to >= date_from', name='ck_education_plan_line_period_dates'),
    sa.ForeignKeyConstraint(['education_plan_line_id'], ['education_plan_line.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('education_plan_line_id', 'date_from', 'date_to', name='uq_education_plan_line_period_dates')
    )
    with op.batch_alter_table('education_plan_line_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_plan_line_period_education_plan_line_id'), ['education_plan_line_id'], unique=False)
        batch_op.create_index('ix_education_plan_line_period_range', ['education_plan_line_id', 'date_from', 'date_to'], unique=False)

    op.create_table('education_plan_line_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_plan_line_id', sa.Integer(), nullable=False),
    sa.Column('scope_kind', sa.String(length=30), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.SmallInteger(), nullable=True),
    sa.Column('profile_code', sa.String(length=80), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('scope_key', sa.String(length=180), nullable=False),
    sa.CheckConstraint("(scope_kind = 'CLASS' AND school_class_id IS NOT NULL AND grade IS NULL AND profile_code IS NULL) OR (scope_kind = 'GRADE' AND school_class_id IS NULL AND grade BETWEEN 1 AND 11 AND profile_code IS NULL) OR (scope_kind = 'PROFILE' AND school_class_id IS NULL AND profile_code IS NOT NULL)", name='ck_education_plan_line_scope_fields'),
    sa.CheckConstraint("scope_kind IN ('CLASS','GRADE','PROFILE')", name='ck_education_plan_line_scope_kind'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['education_plan_line_id'], ['education_plan_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('education_plan_line_id', 'scope_key', name='uq_education_plan_line_scope_key')
    )
    with op.batch_alter_table('education_plan_line_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_plan_line_scope_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_line_scope_education_plan_line_id'), ['education_plan_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_line_scope_school_class_id'), ['school_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_education_plan_line_scope_scope_kind'), ['scope_kind'], unique=False)
        batch_op.create_index('ix_education_plan_scope_grade_profile', ['grade', 'profile_code', 'building_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education_plan_line_scope', schema=None) as batch_op:
        batch_op.drop_index('ix_education_plan_scope_grade_profile')
        batch_op.drop_index(batch_op.f('ix_education_plan_line_scope_scope_kind'))
        batch_op.drop_index(batch_op.f('ix_education_plan_line_scope_school_class_id'))
        batch_op.drop_index(batch_op.f('ix_education_plan_line_scope_education_plan_line_id'))
        batch_op.drop_index(batch_op.f('ix_education_plan_line_scope_building_id'))

    op.drop_table('education_plan_line_scope')
    with op.batch_alter_table('education_plan_line_period', schema=None) as batch_op:
        batch_op.drop_index('ix_education_plan_line_period_range')
        batch_op.drop_index(batch_op.f('ix_education_plan_line_period_education_plan_line_id'))

    op.drop_table('education_plan_line_period')
    with op.batch_alter_table('education_plan_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_education_plan_line_education_plan_id'))
        batch_op.drop_index(batch_op.f('ix_education_plan_line_education_activity_id'))
        batch_op.drop_index(batch_op.f('ix_education_plan_line_component_kind'))
        batch_op.drop_index('ix_education_plan_line_activity_component')

    op.drop_table('education_plan_line')
    with op.batch_alter_table('tariff_version_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariff_version_status_history_tariff_version_id'))
        batch_op.drop_index('ix_tariff_version_history_changed')

    op.drop_table('tariff_version_status_history')
    with op.batch_alter_table('education_plan', schema=None) as batch_op:
        batch_op.drop_index('ix_education_plan_version_kind')
        batch_op.drop_index(batch_op.f('ix_education_plan_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_education_plan_status'))
        batch_op.drop_index(batch_op.f('ix_education_plan_plan_kind'))
        batch_op.drop_index(batch_op.f('ix_education_plan_education_level'))
        batch_op.drop_index(batch_op.f('ix_education_plan_building_id'))

    op.drop_table('education_plan')
    with op.batch_alter_table('tariff_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariff_version_tariff_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_version_status'))
        batch_op.drop_index('ix_tariff_version_cycle_status')

    op.drop_table('tariff_version')
    with op.batch_alter_table('tariff_cycle', schema=None) as batch_op:
        batch_op.drop_index('uq_tariff_cycle_local_year', postgresql_where=sa.text('organization_id IS NOT NULL'), sqlite_where=sa.text('organization_id IS NOT NULL'))
        batch_op.drop_index('uq_tariff_cycle_global_year', postgresql_where=sa.text('organization_id IS NULL'), sqlite_where=sa.text('organization_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_tariff_cycle_status'))
        batch_op.drop_index('ix_tariff_cycle_scope_status')
        batch_op.drop_index(batch_op.f('ix_tariff_cycle_organization_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_cycle_academic_year_id'))

    op.drop_table('tariff_cycle')
    # ### end Alembic commands ###
