"""population snapshots and teaching groups

Revision ID: a4c9e12f7b63
Revises: 7d1f0a6b3c29
Create Date: 2026-07-29 13:35:52.059361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c9e12f7b63'
down_revision = '7d1f0a6b3c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='CURRENT', nullable=False),
    sa.Column('source_kind', sa.String(length=30), server_default='REGISTRY', nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('CURRENT','SUPERSEDED','LOCKED')", name='ck_population_snapshot_status'),
    sa.CheckConstraint('revision_no > 0', name='ck_population_snapshot_revision'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'revision_no', name='uq_population_snapshot_version_revision')
    )
    with op.batch_alter_table('population_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_population_snapshot_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_population_snapshot_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_population_snapshot_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index('uq_population_snapshot_current', ['tariff_version_id'], unique=True, postgresql_where=sa.text("status = 'CURRENT'"), sqlite_where=sa.text("status = 'CURRENT'"))

    op.create_table('population_snapshot_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('source_school_class_id', sa.Integer(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=40), nullable=False),
    sa.Column('grade_snapshot', sa.SmallInteger(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('building_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('student_count', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('student_count >= 0', name='ck_population_snapshot_class_count'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['population_snapshot_id'], ['population_snapshot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_school_class_id'], ['school_class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('population_snapshot_id', 'source_school_class_id', name='uq_population_snapshot_source_class')
    )
    with op.batch_alter_table('population_snapshot_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_population_snapshot_class_building_id'), ['building_id'], unique=False)
        batch_op.create_index('ix_population_snapshot_class_grade_building', ['population_snapshot_id', 'grade_snapshot', 'building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_population_snapshot_class_grade_snapshot'), ['grade_snapshot'], unique=False)
        batch_op.create_index(batch_op.f('ix_population_snapshot_class_population_snapshot_id'), ['population_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_population_snapshot_class_source_school_class_id'), ['source_school_class_id'], unique=False)

    op.create_table('population_snapshot_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population_snapshot_class_id', sa.Integer(), nullable=False),
    sa.Column('source_child_id', sa.Integer(), nullable=False),
    sa.Column('source_enrollment_id', sa.Integer(), nullable=True),
    sa.Column('fio_snapshot', sa.String(length=380), nullable=False),
    sa.Column('status_snapshot', sa.String(length=30), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.CheckConstraint('ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on', name='ck_population_snapshot_enrollment_period'),
    sa.ForeignKeyConstraint(['population_snapshot_class_id'], ['population_snapshot_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['source_enrollment_id'], ['child_enrollment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('population_snapshot_class_id', 'source_child_id', name='uq_population_snapshot_class_child')
    )
    with op.batch_alter_table('population_snapshot_enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_population_snapshot_enrollment_population_snapshot_class_id'), ['population_snapshot_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_population_snapshot_enrollment_source_child_id'), ['source_child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_population_snapshot_enrollment_source_enrollment_id'), ['source_enrollment_id'], unique=False)

    op.create_table('teaching_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('education_activity_id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('composition_mode', sa.String(length=30), server_default='PERSONAL', nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('planned_size', sa.Integer(), nullable=True),
    sa.Column('actual_size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('source_plan_line_id', sa.Integer(), nullable=False),
    sa.Column('source_group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('close_reason', sa.String(length=500), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("composition_mode IN ('PERSONAL','COUNT_ONLY')", name='ck_teaching_group_composition'),
    sa.CheckConstraint("group_type IN ('CLASS','SUBGROUP','METAGROUP','EXTRACURRICULAR_GROUP','ADDITIONAL_GROUP','INDIVIDUAL')", name='ck_teaching_group_type'),
    sa.CheckConstraint("status IN ('DRAFT','READY','CLOSED')", name='ck_teaching_group_status'),
    sa.CheckConstraint('actual_size >= 0', name='ck_teaching_group_actual_size'),
    sa.CheckConstraint('planned_size IS NULL OR planned_size >= 0', name='ck_teaching_group_planned_size'),
    sa.CheckConstraint('revision > 0', name='ck_teaching_group_revision'),
    sa.CheckConstraint('valid_to >= valid_from', name='ck_teaching_group_period'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['education_activity_id'], ['education_activity.id'], ),
    sa.ForeignKeyConstraint(['source_group_id'], ['teaching_group.id'], ),
    sa.ForeignKeyConstraint(['source_plan_line_id'], ['education_plan_line.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'code', name='uq_teaching_group_version_code')
    )
    with op.batch_alter_table('teaching_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_group_building_id'), ['building_id'], unique=False)
        batch_op.create_index('ix_teaching_group_department_building', ['department_id', 'building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_education_activity_id'), ['education_activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_group_type'), ['group_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_source_plan_line_id'), ['source_plan_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_valid_to'), ['valid_to'], unique=False)
        batch_op.create_index('ix_teaching_group_version_activity', ['tariff_version_id', 'education_activity_id'], unique=False)

    op.create_table('teaching_group_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teaching_group_id', sa.Integer(), nullable=False),
    sa.Column('population_snapshot_class_id', sa.Integer(), nullable=False),
    sa.Column('relation_kind', sa.String(length=30), server_default='SOURCE', nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.CheckConstraint("relation_kind IN ('FULL','PARTIAL','SOURCE')", name='ck_teaching_group_class_relation'),
    sa.CheckConstraint('student_count IS NULL OR student_count >= 0', name='ck_teaching_group_class_count'),
    sa.ForeignKeyConstraint(['population_snapshot_class_id'], ['population_snapshot_class.id'], ),
    sa.ForeignKeyConstraint(['teaching_group_id'], ['teaching_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teaching_group_id', 'population_snapshot_class_id', name='uq_teaching_group_snapshot_class')
    )
    with op.batch_alter_table('teaching_group_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_group_class_population_snapshot_class_id'), ['population_snapshot_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_class_teaching_group_id'), ['teaching_group_id'], unique=False)

    op.create_table('teaching_group_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('teaching_group_id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teaching_group_id'], ['teaching_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_group_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_group_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_history_event_code'), ['event_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_history_teaching_group_id'), ['teaching_group_id'], unique=False)

    op.create_table('teaching_group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teaching_group_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('source_kind', sa.String(length=30), server_default='MANUAL', nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.CheckConstraint("source_kind IN ('MANUAL','IMPORT','AUTO')", name='ck_teaching_group_member_source'),
    sa.CheckConstraint('valid_to >= valid_from', name='ck_teaching_group_member_period'),
    sa.ForeignKeyConstraint(['snapshot_enrollment_id'], ['population_snapshot_enrollment.id'], ),
    sa.ForeignKeyConstraint(['teaching_group_id'], ['teaching_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teaching_group_id', 'snapshot_enrollment_id', 'valid_from', name='uq_teaching_group_member_period_start')
    )
    with op.batch_alter_table('teaching_group_member', schema=None) as batch_op:
        batch_op.create_index('ix_teaching_group_member_period', ['teaching_group_id', 'valid_from', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_member_snapshot_enrollment_id'), ['snapshot_enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_group_member_teaching_group_id'), ['teaching_group_id'], unique=False)

    with op.batch_alter_table('education_plan_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weeks_count', sa.Numeric(precision=6, scale=3), nullable=True))
        batch_op.drop_constraint(
            'ck_education_plan_line_hours',
            type_='check',
        )
        batch_op.create_check_constraint(
            'ck_education_plan_line_hours',
            "(weekly_hours IS NOT NULL OR annual_hours IS NOT NULL) "
            "AND (weekly_hours IS NULL OR weekly_hours >= 0) "
            "AND (weeks_count IS NULL OR weeks_count > 0) "
            "AND (annual_hours IS NULL OR annual_hours >= 0)",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education_plan_line', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_education_plan_line_hours',
            type_='check',
        )
        batch_op.drop_column('weeks_count')
        batch_op.create_check_constraint(
            'ck_education_plan_line_hours',
            "(weekly_hours IS NOT NULL OR annual_hours IS NOT NULL) "
            "AND (weekly_hours IS NULL OR weekly_hours >= 0) "
            "AND (annual_hours IS NULL OR annual_hours >= 0)",
        )

    with op.batch_alter_table('teaching_group_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_group_member_teaching_group_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_member_snapshot_enrollment_id'))
        batch_op.drop_index('ix_teaching_group_member_period')

    op.drop_table('teaching_group_member')
    with op.batch_alter_table('teaching_group_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_group_history_teaching_group_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_history_event_code'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_history_changed_at'))

    op.drop_table('teaching_group_history')
    with op.batch_alter_table('teaching_group_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_group_class_teaching_group_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_class_population_snapshot_class_id'))

    op.drop_table('teaching_group_class')
    with op.batch_alter_table('teaching_group', schema=None) as batch_op:
        batch_op.drop_index('ix_teaching_group_version_activity')
        batch_op.drop_index(batch_op.f('ix_teaching_group_valid_to'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_valid_from'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_status'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_source_plan_line_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_group_type'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_education_activity_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_group_department_id'))
        batch_op.drop_index('ix_teaching_group_department_building')
        batch_op.drop_index(batch_op.f('ix_teaching_group_building_id'))

    op.drop_table('teaching_group')
    with op.batch_alter_table('population_snapshot_enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_population_snapshot_enrollment_source_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_population_snapshot_enrollment_source_child_id'))
        batch_op.drop_index(batch_op.f('ix_population_snapshot_enrollment_population_snapshot_class_id'))

    op.drop_table('population_snapshot_enrollment')
    with op.batch_alter_table('population_snapshot_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_population_snapshot_class_source_school_class_id'))
        batch_op.drop_index(batch_op.f('ix_population_snapshot_class_population_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_population_snapshot_class_grade_snapshot'))
        batch_op.drop_index('ix_population_snapshot_class_grade_building')
        batch_op.drop_index(batch_op.f('ix_population_snapshot_class_building_id'))

    op.drop_table('population_snapshot_class')
    with op.batch_alter_table('population_snapshot', schema=None) as batch_op:
        batch_op.drop_index('uq_population_snapshot_current', postgresql_where=sa.text("status = 'CURRENT'"), sqlite_where=sa.text("status = 'CURRENT'"))
        batch_op.drop_index(batch_op.f('ix_population_snapshot_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_population_snapshot_status'))
        batch_op.drop_index(batch_op.f('ix_population_snapshot_snapshot_date'))

    op.drop_table('population_snapshot')
    # ### end Alembic commands ###
