"""workload needs and assignments

Revision ID: c8e71b2d4f90
Revises: a4c9e12f7b63
Create Date: 2026-07-29 16:09:40.164487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c8e71b2d4f90'
down_revision = 'a4c9e12f7b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workload_need',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('teaching_group_id', sa.Integer(), nullable=True),
    sa.Column('education_activity_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=8, scale=3), server_default='0', nullable=False),
    sa.Column('annual_hours', sa.Numeric(precision=10, scale=3), server_default='0', nullable=False),
    sa.Column('need_kind', sa.String(length=30), server_default='PLAN', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("need_kind IN ('PLAN','ADDITIONAL','REPLACEMENT')", name='ck_workload_need_kind'),
    sa.CheckConstraint("status IN ('OPEN','PARTIAL','COVERED','OVERALLOCATED','CANCELLED')", name='ck_workload_need_status'),
    sa.CheckConstraint('date_to >= date_from', name='ck_workload_need_period'),
    sa.CheckConstraint('revision > 0', name='ck_workload_need_revision'),
    sa.CheckConstraint('weekly_hours >= 0 AND annual_hours >= 0', name='ck_workload_need_hours'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['education_activity_id'], ['education_activity.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_settings.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_group_id'], ['teaching_group.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'teaching_group_id', 'date_from', 'date_to', 'need_kind', name='uq_workload_need_group_period_kind')
    )
    with op.batch_alter_table('workload_need', schema=None) as batch_op:
        batch_op.create_index('ix_workload_need_activity_department', ['education_activity_id', 'department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_date_from'), ['date_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_date_to'), ['date_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_education_activity_id'), ['education_activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_need_kind'), ['need_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_teaching_group_id'), ['teaching_group_id'], unique=False)
        batch_op.create_index('ix_workload_need_version_status_department', ['tariff_version_id', 'status', 'department_id'], unique=False)

    op.create_table('workload_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('workload_need_id', sa.Integer(), nullable=False),
    sa.Column('employee_user_id', sa.Integer(), nullable=True),
    sa.Column('position_title', sa.String(length=180), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('assignment_kind', sa.String(length=30), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('annual_hours', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('origin_assignment_id', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(assignment_kind = 'VACANCY' AND employee_user_id IS NULL) OR (assignment_kind <> 'VACANCY' AND employee_user_id IS NOT NULL)", name='ck_workload_assignment_employee'),
    sa.CheckConstraint("assignment_kind IN ('MAIN','SECONDARY','INTERNAL_PART_TIME','EXTERNAL_PART_TIME','SUBSTITUTE','VACANCY')", name='ck_workload_assignment_kind'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','CANCELLED')", name='ck_workload_assignment_status'),
    sa.CheckConstraint('date_to >= date_from', name='ck_workload_assignment_period'),
    sa.CheckConstraint('revision > 0', name='ck_workload_assignment_revision'),
    sa.CheckConstraint('weekly_hours >= 0 AND annual_hours >= 0', name='ck_workload_assignment_hours'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_settings.id'], ),
    sa.ForeignKeyConstraint(['origin_assignment_id'], ['workload_assignment.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workload_need_id'], ['workload_need.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workload_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workload_assignment_assignment_kind'), ['assignment_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_date_from'), ['date_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_date_to'), ['date_to'], unique=False)
        batch_op.create_index('ix_workload_assignment_department_building', ['department_id', 'building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_employee_user_id'), ['employee_user_id'], unique=False)
        batch_op.create_index('ix_workload_assignment_need_status', ['workload_need_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index('ix_workload_assignment_version_employee_status', ['tariff_version_id', 'employee_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_workload_need_id'), ['workload_need_id'], unique=False)

    op.create_table('workload_need_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workload_need_id', sa.Integer(), nullable=False),
    sa.Column('education_plan_line_id', sa.Integer(), nullable=False),
    sa.Column('source_weekly_hours', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('source_annual_hours', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('source_kind', sa.String(length=30), server_default='DIRECT', nullable=False),
    sa.CheckConstraint("source_kind IN ('DIRECT','DIVISION','MERGE','MANUAL')", name='ck_workload_need_source_kind'),
    sa.CheckConstraint('source_weekly_hours >= 0 AND source_annual_hours >= 0', name='ck_workload_need_source_hours'),
    sa.ForeignKeyConstraint(['education_plan_line_id'], ['education_plan_line.id'], ),
    sa.ForeignKeyConstraint(['workload_need_id'], ['workload_need.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workload_need_id', 'education_plan_line_id', 'source_kind', name='uq_workload_need_source_line_kind')
    )
    with op.batch_alter_table('workload_need_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workload_need_source_education_plan_line_id'), ['education_plan_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_need_source_workload_need_id'), ['workload_need_id'], unique=False)

    op.create_table('workload_assignment_change',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workload_assignment_id', sa.Integer(), nullable=False),
    sa.Column('change_kind', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('before_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint("change_kind IN ('CREATE','UPDATE','SPLIT','TRANSFER','CANCEL')", name='ck_workload_assignment_change_kind'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workload_assignment_id'], ['workload_assignment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workload_assignment_change', schema=None) as batch_op:
        batch_op.create_index('ix_workload_assignment_change_assignment_time', ['workload_assignment_id', 'changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_change_change_kind'), ['change_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_change_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_assignment_change_workload_assignment_id'), ['workload_assignment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload_assignment_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workload_assignment_change_workload_assignment_id'))
        batch_op.drop_index(batch_op.f('ix_workload_assignment_change_changed_at'))
        batch_op.drop_index(batch_op.f('ix_workload_assignment_change_change_kind'))
        batch_op.drop_index('ix_workload_assignment_change_assignment_time')

    op.drop_table('workload_assignment_change')
    with op.batch_alter_table('workload_need_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workload_need_source_workload_need_id'))
        batch_op.drop_index(batch_op.f('ix_workload_need_source_education_plan_line_id'))

    op.drop_table('workload_need_source')
    with op.batch_alter_table('workload_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workload_assignment_workload_need_id'))
        batch_op.drop_index('ix_workload_assignment_version_employee_status')
        batch_op.drop_index(batch_op.f('ix_workload_assignment_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_workload_assignment_status'))
        batch_op.drop_index(batch_op.f('ix_workload_assignment_organization_id'))
        batch_op.drop_index('ix_workload_assignment_need_status')
        batch_op.drop_index(batch_op.f('ix_workload_assignment_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_workload_assignment_department_id'))
        batch_op.drop_index('ix_workload_assignment_department_building')
        batch_op.drop_index(batch_op.f('ix_workload_assignment_date_to'))
        batch_op.drop_index(batch_op.f('ix_workload_assignment_date_from'))
        batch_op.drop_index(batch_op.f('ix_workload_assignment_building_id'))
        batch_op.drop_index(batch_op.f('ix_workload_assignment_assignment_kind'))

    op.drop_table('workload_assignment')
    with op.batch_alter_table('workload_need', schema=None) as batch_op:
        batch_op.drop_index('ix_workload_need_version_status_department')
        batch_op.drop_index(batch_op.f('ix_workload_need_teaching_group_id'))
        batch_op.drop_index(batch_op.f('ix_workload_need_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_workload_need_status'))
        batch_op.drop_index(batch_op.f('ix_workload_need_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workload_need_need_kind'))
        batch_op.drop_index(batch_op.f('ix_workload_need_education_activity_id'))
        batch_op.drop_index(batch_op.f('ix_workload_need_department_id'))
        batch_op.drop_index(batch_op.f('ix_workload_need_date_to'))
        batch_op.drop_index(batch_op.f('ix_workload_need_date_from'))
        batch_op.drop_index(batch_op.f('ix_workload_need_building_id'))
        batch_op.drop_index('ix_workload_need_activity_department')

    op.drop_table('workload_need')
    # ### end Alembic commands ###
