"""tariff workflow approval and documents

Revision ID: e42b8c6f1d73
Revises: d31a7f4e9b20
Create Date: 2026-07-29 19:42:25.564068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e42b8c6f1d73'
down_revision = 'd31a7f4e9b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_document_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('calculation_run_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('employee_user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('scope_key', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('version_checksum', sa.String(length=128), nullable=True),
    sa.Column('template_version', sa.String(length=80), nullable=False),
    sa.Column('generation_parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("document_type IN ('SUMMARY_TARIFF','PERSONAL_TARIFF','REVIEW_PROTOCOL','APPROVAL_SHEET','ORDER_DRAFT','CHANGE_ORDER_DRAFT')", name='ck_tariff_document_artifact_type'),
    sa.CheckConstraint("status IN ('PROJECT','OFFICIAL','ARCHIVED','ERROR')", name='ck_tariff_document_artifact_status'),
    sa.CheckConstraint('revision_no > 0 AND file_size >= 0', name='ck_tariff_document_artifact_values'),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['tariff_calculation_run.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'document_type', 'scope_key', 'revision_no', name='uq_tariff_document_artifact_scope_revision')
    )
    with op.batch_alter_table('tariff_document_artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_document_artifact_calculation_run_id'), ['calculation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_document_artifact_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_document_artifact_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_document_artifact_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_document_artifact_employee_user_id'), ['employee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_document_artifact_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_document_artifact_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index('ix_tariff_document_artifact_version_type_status', ['tariff_version_id', 'document_type', 'status'], unique=False)

    op.create_table('tariff_validation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('calculation_run_id', sa.Integer(), nullable=True),
    sa.Column('run_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rule_set_version', sa.String(length=80), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('summary_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PASSED','FAILED','TECHNICAL_ERROR')", name='ck_tariff_validation_run_status'),
    sa.CheckConstraint('run_no > 0', name='ck_tariff_validation_run_number'),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['tariff_calculation_run.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'run_no', name='uq_tariff_validation_run_version_number')
    )
    with op.batch_alter_table('tariff_validation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_validation_run_calculation_run_id'), ['calculation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_validation_run_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_validation_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_validation_run_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index('ix_tariff_validation_run_version_status', ['tariff_version_id', 'status'], unique=False)

    op.create_table('tariff_review_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False),
    sa.Column('started_by_user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('OPEN','RETURNED','COMPLETED')", name='ck_tariff_review_cycle_status'),
    sa.CheckConstraint('round_no > 0', name='ck_tariff_review_cycle_round'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['tariff_validation_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'round_no', name='uq_tariff_review_cycle_version_round')
    )
    with op.batch_alter_table('tariff_review_cycle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_review_cycle_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_cycle_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_cycle_validation_run_id'), ['validation_run_id'], unique=False)

    op.create_table('tariff_validation_issue',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=700), nullable=False),
    sa.Column('remediation', sa.String(length=700), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.CheckConstraint("severity IN ('BLOCKER','ERROR','WARNING','INFO')", name='ck_tariff_validation_issue_severity'),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['tariff_validation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('validation_run_id', 'fingerprint', name='uq_tariff_validation_issue_fingerprint')
    )
    with op.batch_alter_table('tariff_validation_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_validation_issue_rule_code'), ['rule_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_validation_issue_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_validation_issue_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_validation_issue_validation_run_id'), ['validation_run_id'], unique=False)
        batch_op.create_index('ix_tariff_validation_issue_version_severity', ['tariff_version_id', 'severity'], unique=False)

    op.create_table('tariff_approval_decision',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('review_cycle_id', sa.Integer(), nullable=False),
    sa.Column('decision_no', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('version_checksum', sa.String(length=128), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED','REJECTED')", name='ck_tariff_approval_decision_value'),
    sa.CheckConstraint('decision_no > 0', name='ck_tariff_approval_decision_number'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['review_cycle_id'], ['tariff_review_cycle.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'decision_no', name='uq_tariff_approval_decision_version_number')
    )
    with op.batch_alter_table('tariff_approval_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_approval_decision_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_approval_decision_review_cycle_id'), ['review_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_approval_decision_tariff_version_id'), ['tariff_version_id'], unique=False)

    op.create_table('tariff_review_comment',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('review_cycle_id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('review_stage', sa.String(length=30), nullable=False),
    sa.Column('comment_kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('answered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("comment_kind IN ('BLOCKING','RECOMMENDATION')", name='ck_tariff_review_comment_kind'),
    sa.CheckConstraint("review_stage IN ('ACADEMIC','HR','FINANCE')", name='ck_tariff_review_comment_stage'),
    sa.CheckConstraint("status IN ('OPEN','ANSWERED','CLOSED')", name='ck_tariff_review_comment_status'),
    sa.ForeignKeyConstraint(['answered_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['review_cycle_id'], ['tariff_review_cycle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariff_review_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_review_comment_comment_kind'), ['comment_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_comment_review_cycle_id'), ['review_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_comment_review_stage'), ['review_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_comment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_comment_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index('ix_tariff_review_comment_version_status', ['tariff_version_id', 'status'], unique=False)

    op.create_table('tariff_review_decision',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('review_cycle_id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('review_stage', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('validation_input_hash', sa.String(length=128), nullable=False),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED','CHANGES_REQUESTED')", name='ck_tariff_review_decision_value'),
    sa.CheckConstraint("review_stage IN ('ACADEMIC','HR','FINANCE')", name='ck_tariff_review_decision_stage'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['review_cycle_id'], ['tariff_review_cycle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_cycle_id', 'review_stage', name='uq_tariff_review_decision_cycle_stage')
    )
    with op.batch_alter_table('tariff_review_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_review_decision_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_decision_review_cycle_id'), ['review_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_decision_review_stage'), ['review_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_tariff_review_decision_tariff_version_id'), ['tariff_version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff_review_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariff_review_decision_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_decision_review_stage'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_decision_review_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_decision_decision'))

    op.drop_table('tariff_review_decision')
    with op.batch_alter_table('tariff_review_comment', schema=None) as batch_op:
        batch_op.drop_index('ix_tariff_review_comment_version_status')
        batch_op.drop_index(batch_op.f('ix_tariff_review_comment_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_comment_status'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_comment_review_stage'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_comment_review_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_comment_comment_kind'))

    op.drop_table('tariff_review_comment')
    with op.batch_alter_table('tariff_approval_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariff_approval_decision_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_approval_decision_review_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_approval_decision_decision'))

    op.drop_table('tariff_approval_decision')
    with op.batch_alter_table('tariff_validation_issue', schema=None) as batch_op:
        batch_op.drop_index('ix_tariff_validation_issue_version_severity')
        batch_op.drop_index(batch_op.f('ix_tariff_validation_issue_validation_run_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_validation_issue_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_validation_issue_severity'))
        batch_op.drop_index(batch_op.f('ix_tariff_validation_issue_rule_code'))

    op.drop_table('tariff_validation_issue')
    with op.batch_alter_table('tariff_review_cycle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariff_review_cycle_validation_run_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_cycle_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_review_cycle_status'))

    op.drop_table('tariff_review_cycle')
    with op.batch_alter_table('tariff_validation_run', schema=None) as batch_op:
        batch_op.drop_index('ix_tariff_validation_run_version_status')
        batch_op.drop_index(batch_op.f('ix_tariff_validation_run_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_validation_run_status'))
        batch_op.drop_index(batch_op.f('ix_tariff_validation_run_input_hash'))
        batch_op.drop_index(batch_op.f('ix_tariff_validation_run_calculation_run_id'))

    op.drop_table('tariff_validation_run')
    with op.batch_alter_table('tariff_document_artifact', schema=None) as batch_op:
        batch_op.drop_index('ix_tariff_document_artifact_version_type_status')
        batch_op.drop_index(batch_op.f('ix_tariff_document_artifact_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_document_artifact_status'))
        batch_op.drop_index(batch_op.f('ix_tariff_document_artifact_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_document_artifact_document_type'))
        batch_op.drop_index(batch_op.f('ix_tariff_document_artifact_department_id'))
        batch_op.drop_index(batch_op.f('ix_tariff_document_artifact_checksum_sha256'))
        batch_op.drop_index(batch_op.f('ix_tariff_document_artifact_calculation_run_id'))

    op.drop_table('tariff_document_artifact')
    # ### end Alembic commands ###
