"""department workload source integration

Revision ID: f53c9d7a2e84
Revises: e42b8c6f1d73
Create Date: 2026-07-29 20:15:17.216200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f53c9d7a2e84'
down_revision = 'e42b8c6f1d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workload_source_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), server_default='LEGACY', nullable=False),
    sa.Column('selected_tariff_version_id', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source_mode IN ('LEGACY','COMPARE','INTERNAL')", name='ck_workload_source_setting_mode'),
    sa.CheckConstraint('revision > 0', name='ck_workload_source_setting_revision'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_settings.id'], ),
    sa.ForeignKeyConstraint(['selected_tariff_version_id'], ['tariff_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workload_source_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workload_source_setting_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_source_setting_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_source_setting_selected_tariff_version_id'), ['selected_tariff_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_source_setting_source_mode'), ['source_mode'], unique=False)
        batch_op.create_index('uq_workload_source_setting_global_year', ['academic_year_id'], unique=True, postgresql_where=sa.text('organization_id IS NULL'), sqlite_where=sa.text('organization_id IS NULL'))
        batch_op.create_index('uq_workload_source_setting_local_year', ['organization_id', 'academic_year_id'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'), sqlite_where=sa.text('organization_id IS NOT NULL'))

    op.create_table('workload_reconciliation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('tariff_version_id', sa.Integer(), nullable=False),
    sa.Column('calculation_run_id', sa.Integer(), nullable=False),
    sa.Column('run_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='RUNNING', nullable=False),
    sa.Column('tolerance_hours', sa.Numeric(precision=8, scale=3), server_default='0.001', nullable=False),
    sa.Column('legacy_row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('internal_row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matched_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocking_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('legacy_weekly_hours', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('internal_weekly_hours', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('summary_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('RUNNING','PASSED','FAILED','TECHNICAL_ERROR')", name='ck_workload_reconciliation_run_status'),
    sa.CheckConstraint('legacy_row_count >= 0 AND internal_row_count >= 0 AND matched_count >= 0 AND blocking_count >= 0', name='ck_workload_reconciliation_run_counts'),
    sa.CheckConstraint('run_no > 0 AND tolerance_hours >= 0', name='ck_workload_reconciliation_run_values'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['tariff_calculation_run.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_settings.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_version_id', 'run_no', name='uq_workload_reconciliation_run_version_number')
    )
    with op.batch_alter_table('workload_reconciliation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_run_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_run_calculation_run_id'), ['calculation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_run_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_run_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index('ix_workload_reconciliation_year_status', ['academic_year_id', 'status'], unique=False)

    op.create_table('workload_reconciliation_item',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('match_key', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('employee_user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('education_activity_id', sa.Integer(), nullable=True),
    sa.Column('legacy_weekly_hours', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('internal_weekly_hours', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('difference_hours', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.CheckConstraint("status IN ('MATCH','HOURS_MISMATCH','LEGACY_ONLY','INTERNAL_ONLY','UNMAPPED_ACTIVITY')", name='ck_workload_reconciliation_item_status'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['education_activity_id'], ['education_activity.id'], ),
    sa.ForeignKeyConstraint(['employee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['workload_reconciliation_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'match_key', name='uq_workload_reconciliation_item_key')
    )
    with op.batch_alter_table('workload_reconciliation_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_item_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_item_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_item_education_activity_id'), ['education_activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_item_employee_user_id'), ['employee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_item_reconciliation_run_id'), ['reconciliation_run_id'], unique=False)
        batch_op.create_index('ix_workload_reconciliation_item_run_status', ['reconciliation_run_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_item_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_reconciliation_item_subject_id'), ['subject_id'], unique=False)

    op.create_table('workload_source_transition',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('workload_source_setting_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=True),
    sa.Column('tariff_version_id', sa.Integer(), nullable=True),
    sa.Column('from_mode', sa.String(length=20), nullable=False),
    sa.Column('to_mode', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("from_mode IN ('LEGACY','COMPARE','INTERNAL') AND to_mode IN ('LEGACY','COMPARE','INTERNAL')", name='ck_workload_source_transition_modes'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['workload_reconciliation_run.id'], ),
    sa.ForeignKeyConstraint(['tariff_version_id'], ['tariff_version.id'], ),
    sa.ForeignKeyConstraint(['workload_source_setting_id'], ['workload_source_setting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workload_source_transition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workload_source_transition_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_source_transition_reconciliation_run_id'), ['reconciliation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_source_transition_tariff_version_id'), ['tariff_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workload_source_transition_workload_source_setting_id'), ['workload_source_setting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload_source_transition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workload_source_transition_workload_source_setting_id'))
        batch_op.drop_index(batch_op.f('ix_workload_source_transition_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_workload_source_transition_reconciliation_run_id'))
        batch_op.drop_index(batch_op.f('ix_workload_source_transition_changed_at'))

    op.drop_table('workload_source_transition')
    with op.batch_alter_table('workload_reconciliation_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_item_subject_id'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_item_status'))
        batch_op.drop_index('ix_workload_reconciliation_item_run_status')
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_item_reconciliation_run_id'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_item_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_item_education_activity_id'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_item_department_id'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_item_building_id'))

    op.drop_table('workload_reconciliation_item')
    with op.batch_alter_table('workload_reconciliation_run', schema=None) as batch_op:
        batch_op.drop_index('ix_workload_reconciliation_year_status')
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_run_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_run_status'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_run_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_run_calculation_run_id'))
        batch_op.drop_index(batch_op.f('ix_workload_reconciliation_run_academic_year_id'))

    op.drop_table('workload_reconciliation_run')
    with op.batch_alter_table('workload_source_setting', schema=None) as batch_op:
        batch_op.drop_index('uq_workload_source_setting_local_year', postgresql_where=sa.text('organization_id IS NOT NULL'), sqlite_where=sa.text('organization_id IS NOT NULL'))
        batch_op.drop_index('uq_workload_source_setting_global_year', postgresql_where=sa.text('organization_id IS NULL'), sqlite_where=sa.text('organization_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_workload_source_setting_source_mode'))
        batch_op.drop_index(batch_op.f('ix_workload_source_setting_selected_tariff_version_id'))
        batch_op.drop_index(batch_op.f('ix_workload_source_setting_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workload_source_setting_academic_year_id'))

    op.drop_table('workload_source_setting')
    # ### end Alembic commands ###
