name: school_support_mobile
description: Mobile application for the school support portal.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
