"""academic years, buildings, classes, enrollment

Revision ID: 859d6b9ccb7f
Revises: 
Create Date: 2026-03-03 12:31:27.939654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859d6b9ccb7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_comment_author_id'))
        batch_op.drop_index(batch_op.f('ix_child_comment_child_id'))

    op.drop_table('child_comment')
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('is_low',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_az',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_disabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('disability_mse',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['closed_by_user_id'], ['id'])
        batch_op.drop_column('responsible_user_id')
        batch_op.drop_column('comment')
        batch_op.drop_column('closed_date')
        batch_op.drop_column('detected_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('closed_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('responsible_user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['responsible_user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.alter_column('disability_mse',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_disabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_az',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_low',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('middle_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.create_table('child_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_comment_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_comment_author_id'), ['author_id'], unique=False)

    # ### end Alembic commands ###
