"""Shared constants for the stabilized v71 architecture."""

PER_PAGE_OPTIONS = (20, 30, 50, 100, "all")
DEFAULT_PER_PAGE = 20

ROLE_ADMIN = "ADMIN"
ROLE_CLASS_TEACHER = "CLASS_TEACHER"
ROLE_KPP = "KPP"
ROLE_SUPPORT = "SUPPORT"
ROLE_METHODIST = "METHODIST"
ROLE_SYSTEM = "SYSTEM"

SYSTEM_ROLES = (
    ROLE_ADMIN,
    ROLE_CLASS_TEACHER,
    ROLE_KPP,
    ROLE_SUPPORT,
    ROLE_METHODIST,
    ROLE_SYSTEM,
)
